version: '3'
services:
  postgres-compose:
    image: postgres:latest
    container_name: postgres-compose
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
    ports:
      - 54321:5432
    volumes:
      - my-volume:/var/lib/postgresql/data

  api:
    build:
      context: ./todo-api
      dockerfile: Dockerfile
    container_name: api
    environment:
      - HOST=host.docker.internal
      - PORT=54321
      - USER_NAME=postgres
      - PASS_WORD=123456
      - DATABASE_NAME=postgres
    ports:
      - 3002:3001
    depends_on:
      - postgres-compose
  web:
    build:
      context: ./fe
      dockerfile: Dockerfile
    container_name: web
    ports:
      - 3000:3000
    depends_on:
      - api

volumes:
  my-volume:
