# Sử dụng image cơ sở PostgreSQL
FROM postgres:latest

# Môi trường biến
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=123456
ENV POSTGRES_DB=postgres

# Sao chép các script SQL vào thư mục /docker-entrypoint-initdb.d/ trong image
# Cổng lắng nghe mặc định cho PostgreSQL
EXPOSE 5432