FROM node:16

# Create app directory
WORKDIR /app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --omit=dev

# Bundle app source
COPY . .
ENV HOST=host.docker.internal
ENV PORT=54321
ENV USER_NAME=postgres
ENV PASS_WORD=123456
ENV DATABASE_NAME=postgres

EXPOSE 3001
CMD ["npm", "run", "start:dev"]